name: PHPUnit

on:
  push:
  pull_request:

jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit
